favicon: null
name: RusNikita
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6659575
  brandStrength: 0.9002908247057348
  lightness: 0.8425532
  brandColors:
    - '#000000'
    - '#DEBF9B'
    - '#6E5D4A'
    - '#30FFFF'
    - '#FCFCFB'
  rhythmicContrast: 0.3106383
typography_spectrum: 0.106383
layout_spectrum: 0.8506463724188507
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
